### ISSUE TITLE
jdk8运行报错-无法正常扫描

### ISSUE THREAD

**Issue by zangcc** [Y5neKO/ShiroEXP#3]
<img width="967" alt="image" src="https://github.com/user-attachments/assets/bb22f828-0a2f-4d56-b55d-7f8791404f52">

报错信息：
`Exception in thread "main" com.alibaba.fastjson.JSONException: syntax error, pos 1, line 1, column 2<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The requested resource [&#47;new_gen] is not available</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/9.0.93</h3></body></html>
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1510)
	at com.alibaba.fastjson.parser.DefaultJSONParser.parse(DefaultJSONParser.java:1390)
	at com.alibaba.fastjson.JSON.parse(JSON.java:181)
	at com.alibaba.fastjson.JSON.parse(JSON.java:191)
	at com.alibaba.fastjson.JSON.parse(JSON.java:147)
	at com.alibaba.fastjson.JSON.parseObject(JSON.java:252)
	at com.y5neko.shiroexp.misc.DnslogConfig.getDnslogDomain(DnslogConfig.java:16)
	at com.y5neko.shiroexp.payloads.Shiro550VerifyByURLDNS.verify(Shiro550VerifyByURLDNS.java:20)
	at com.y5neko.shiroexp.Main.main(Main.java:84)
	at com.y5neko.shiroexp.Console.main(Console.java:9)`

**Comment by Y5neKO** [comment]
你好，这里是因为dnslog平台的接口发生了变化所以用不了，扫描漏洞可以尝试直接爆破回显链，如果有用urldns验证出网的需求可以等我修复

**Comment by Y5neKO** [comment]
v0.2已修复bug.
